//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusAccountOptimizer2.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DofusAccountOptimizer2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRA.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Composition.
        /// </summary>
        public static string add_composition {
            get {
                return ResourceManager.GetString("add_composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change icons.
        /// </summary>
        public static string change_icons {
            get {
                return ResourceManager.GetString("change_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change icons automatically.
        /// </summary>
        public static string change_icons_auto {
            get {
                return ResourceManager.GetString("change_icons_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Character not found.
        /// </summary>
        public static string character_not_found {
            get {
                return ResourceManager.GetString("character_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IOP.
        /// </summary>
        public static string class_10 {
            get {
                return ResourceManager.GetString("class_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OSAMODAS.
        /// </summary>
        public static string class_11 {
            get {
                return ResourceManager.GetString("class_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OUGINAK.
        /// </summary>
        public static string class_12 {
            get {
                return ResourceManager.GetString("class_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PANDAWA.
        /// </summary>
        public static string class_13 {
            get {
                return ResourceManager.GetString("class_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ROGUE.
        /// </summary>
        public static string class_14 {
            get {
                return ResourceManager.GetString("class_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SACRIER.
        /// </summary>
        public static string class_15 {
            get {
                return ResourceManager.GetString("class_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SADIDA.
        /// </summary>
        public static string class_16 {
            get {
                return ResourceManager.GetString("class_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SRAM.
        /// </summary>
        public static string class_17 {
            get {
                return ResourceManager.GetString("class_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FOGGERNAUT.
        /// </summary>
        public static string class_18 {
            get {
                return ResourceManager.GetString("class_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XELOR.
        /// </summary>
        public static string class_19 {
            get {
                return ResourceManager.GetString("class_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRA.
        /// </summary>
        public static string class_2 {
            get {
                return ResourceManager.GetString("class_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MASQUERAIDER.
        /// </summary>
        public static string class_20 {
            get {
                return ResourceManager.GetString("class_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ECAFLIP.
        /// </summary>
        public static string class_3 {
            get {
                return ResourceManager.GetString("class_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIOTROPE.
        /// </summary>
        public static string class_4 {
            get {
                return ResourceManager.GetString("class_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENIRIPSA.
        /// </summary>
        public static string class_5 {
            get {
                return ResourceManager.GetString("class_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENUTROF.
        /// </summary>
        public static string class_6 {
            get {
                return ResourceManager.GetString("class_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECA.
        /// </summary>
        public static string class_7 {
            get {
                return ResourceManager.GetString("class_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FORGELANCE.
        /// </summary>
        public static string class_8 {
            get {
                return ResourceManager.GetString("class_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HUPPERMAGE.
        /// </summary>
        public static string class_9 {
            get {
                return ResourceManager.GetString("class_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Composition.
        /// </summary>
        public static string edit_composition {
            get {
                return ResourceManager.GetString("edit_composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string edit_key {
            get {
                return ResourceManager.GetString("edit_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable Keyboard.
        /// </summary>
        public static string enable_keyboard {
            get {
                return ResourceManager.GetString("enable_keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable Mouse.
        /// </summary>
        public static string enable_mouse {
            get {
                return ResourceManager.GetString("enable_mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have already a Character with this name.
        /// </summary>
        public static string error_already_exists {
            get {
                return ResourceManager.GetString("error_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This Key Shortcut is already in use.
        /// </summary>
        public static string error_keybinding_duplicated {
            get {
                return ResourceManager.GetString("error_keybinding_duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have already 8 characters, delete at least one if you want to add more.
        /// </summary>
        public static string error_max_characters {
            get {
                return ResourceManager.GetString("error_max_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group the Windows.
        /// </summary>
        public static string group_windows {
            get {
                return ResourceManager.GetString("group_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key to switch between windows.
        /// </summary>
        public static string key_swap_windows {
            get {
                return ResourceManager.GetString("key_swap_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close All the Windows.
        /// </summary>
        public static string kill_windows {
            get {
                return ResourceManager.GetString("kill_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max 3 Keys.
        /// </summary>
        public static string max_key_codes {
            get {
                return ResourceManager.GetString("max_key_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press the keys you want to use to siwtch between and then press save (3 keys Max).
        /// </summary>
        public static string message_keys {
            get {
                return ResourceManager.GetString("message_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Class.
        /// </summary>
        public static string name_class {
            get {
                return ResourceManager.GetString("name_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order the Windows.
        /// </summary>
        public static string order_windows {
            get {
                return ResourceManager.GetString("order_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order The Windows when the composition changes.
        /// </summary>
        public static string order_windows_change {
            get {
                return ResourceManager.GetString("order_windows_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Make Sure to execute this application as Administrator.
        /// </summary>
        public static string privilege_error {
            get {
                return ResourceManager.GetString("privilege_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Composition.
        /// </summary>
        public static string remove_composition {
            get {
                return ResourceManager.GetString("remove_composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Selected.
        /// </summary>
        public static string remove_selected {
            get {
                return ResourceManager.GetString("remove_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Separate the Windows.
        /// </summary>
        public static string separate_windows {
            get {
                return ResourceManager.GetString("separate_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use Taskbar Big Icons.
        /// </summary>
        public static string taskbar_icons {
            get {
                return ResourceManager.GetString("taskbar_icons", resourceCulture);
            }
        }
    }
}
