//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusAccountOptimizer2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DofusAccountOptimizer2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRA.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change icons.
        /// </summary>
        public static string change_icons {
            get {
                return ResourceManager.GetString("change_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change icons automatically.
        /// </summary>
        public static string change_icons_auto {
            get {
                return ResourceManager.GetString("change_icons_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOP.
        /// </summary>
        public static string class_10 {
            get {
                return ResourceManager.GetString("class_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSAMODAS.
        /// </summary>
        public static string class_11 {
            get {
                return ResourceManager.GetString("class_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUGINAK.
        /// </summary>
        public static string class_12 {
            get {
                return ResourceManager.GetString("class_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANDAWA.
        /// </summary>
        public static string class_13 {
            get {
                return ResourceManager.GetString("class_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROGUE.
        /// </summary>
        public static string class_14 {
            get {
                return ResourceManager.GetString("class_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SACRIER.
        /// </summary>
        public static string class_15 {
            get {
                return ResourceManager.GetString("class_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SADIDA.
        /// </summary>
        public static string class_16 {
            get {
                return ResourceManager.GetString("class_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRAM.
        /// </summary>
        public static string class_17 {
            get {
                return ResourceManager.GetString("class_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOGGERNAUT.
        /// </summary>
        public static string class_18 {
            get {
                return ResourceManager.GetString("class_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XELOR.
        /// </summary>
        public static string class_19 {
            get {
                return ResourceManager.GetString("class_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRA.
        /// </summary>
        public static string class_2 {
            get {
                return ResourceManager.GetString("class_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASQUERAIDER.
        /// </summary>
        public static string class_20 {
            get {
                return ResourceManager.GetString("class_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECAFLIP.
        /// </summary>
        public static string class_3 {
            get {
                return ResourceManager.GetString("class_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIOTROPE.
        /// </summary>
        public static string class_4 {
            get {
                return ResourceManager.GetString("class_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENIRIPSA.
        /// </summary>
        public static string class_5 {
            get {
                return ResourceManager.GetString("class_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENUTROF.
        /// </summary>
        public static string class_6 {
            get {
                return ResourceManager.GetString("class_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECA.
        /// </summary>
        public static string class_7 {
            get {
                return ResourceManager.GetString("class_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORGELANCE.
        /// </summary>
        public static string class_8 {
            get {
                return ResourceManager.GetString("class_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUPPERMAGE.
        /// </summary>
        public static string class_9 {
            get {
                return ResourceManager.GetString("class_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key to switch between windows.
        /// </summary>
        public static string key_swap_windows {
            get {
                return ResourceManager.GetString("key_swap_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string name_class {
            get {
                return ResourceManager.GetString("name_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order the Windows.
        /// </summary>
        public static string order_windows {
            get {
                return ResourceManager.GetString("order_windows", resourceCulture);
            }
        }
    }
}
